# Generated by Django 5.1.7 on 2025-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('poster', models.ImageField(upload_to='')),
                ('about', models.TextField(blank=True)),
            ],
        ),
    ]
