# Generated by Django 5.1.7 on 2025-04-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movies',
        ),
    ]
