# Generated by Django 5.1.7 on 2025-04-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0002_rename_movie_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
